### ISSUE TITLE
Simulate RGB Camera Feed in Unity

### ISSUE THREAD

**Issue by Roozki** [UBC-Snowbots/SimFlake#1]
We need to publish a ROS2 image feed from Unity.
This issue is for the regular RGB camera feed.

In ROS, a camera feed is handled via an image msg. 
Note, there is also a camera message, that also includes data about the physical camera. For this task, we just care about an image topic, but would be good to also investigate how we can publish the data frames as a ros2 camera msg.

Hard Requirements: (The task is not finished until: )
- We have a C# script that we can attach to a camera object in unity, and have that data publish to ROS2 on game start.

Soft Requirements (ideally, this task results in):
- Controllable Framerate
- Topic is set as a parameter that we can edit in Unity's inspector, or specific to the camera object's name "/<camera_name>/image_raw"
- Ability to output compressed images, instead of just raw data.

**Comment by moyni-han** [comment]
https://vimeo.com/649652075

This video might be helpful for the Camera integration

**Comment by moyni-han** [comment]
https://medium.com/google-developers/real-time-image-capture-in-unity-458de1364a4c

**Comment by moyni-han** [comment]
Only workin in 420p so far...
