### ISSUE TITLE
Figure out how to put ArUco codes in Unity

### ISSUE THREAD

**Issue by Roozki** [UBC-Snowbots/SimFlake#2]

**Comment by Roozki** [comment]
End point of this task is having a generic ArUco code asset, that we can drag into the scene, then select the ID

**Comment by moyni-han** [comment]
see https://github.com/UBC-Snowbots/SimFlake/commit/8766d88e2df86a733ead473ae9584109c32034ee

**Comment by moyni-han** [comment]
Currently has all possible ArUco markers that will be present in the competition... rotates on a 30 second basis... but can easily be changed to stay on singular marker

**Comment by Roozki** [comment]
Awesome work
